services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nghia
      MYSQL_DATABASE: nghia
    command: --default-authentication-plugin=mysql_native_password



    # command: --init-file /init.sql
    # volumes:
    #   - ./mysql/init.sql:/init.sql
    # logging:
    #   driver: none

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: nghia
    # logging:
    #   driver: none
